version: '3'
services:
  newscast_services:
    image: creativitykills/nginx-php-server
    container_name: newscast-api
    ports:
      - "44699:80"
    volumes:
      - ./:/var/www
    networks:
      - backend

  mysql:
    container_name: newscast-api-mysql
    image: mysql:5.7
    ports:
      - "33063:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=ajimoti"
    volumes:
      - "./db/mysql/data:/var/lib/mysql"
      - "./db/mysql/initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - backend
  pma:
    container_name: newscast-api-pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "44666:80"
    environment:
      - "PMA_HOST=newscast-api-mysql"
      - "MYSQL_DATABASE=newscast"
      - "MYSQL_ROOT_PASSWORD=ajimoti"
    networks:
      - backend

networks:
  backend:
    driver: bridge
